#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "husky - running pre-push hook"

# Turn off immediate exit on error.
set +e

# Get the diff of the current branch and its upstream branch and store it in
# the "difference" variable. This will exit nonzero if there is no upstream set.
difference=$(git diff @{push} --name-only 2>&1 | (read difference; echo $difference ))
# Capture the exit code of the git diff command.
result=$?

# Turn on immediate exit on error.
set -e

if [ $result -ne 0 ]; then
  if [ $result -eq 128 ]; then
    echo 'husky - No upstream branch set. Skipping test run.'
  else
    echo $difference
    echo 'husky - pre-push hook completed unsuccessfully.'
    exit $result
  fi
else
  if [ "$difference" == "" ]; then
    echo $difference
    echo 'husky - No difference to upstream branch. Skipping test run.'
  else
    echo "husky - running related tests for files \"$difference\""
    pnpm vitest related --run $difference
  fi
fi

echo 'husky - pre-push hook completed successfully.'
